services:
  gcuflashing:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcuflashing:latest
    container_name: gcuflashing

    network_mode: host

    privileged: true
    group_add:
      - dialout

    devices:
      - /dev:/dev
      - /run/udev:/run/udev

    volumes:
      - ./entrypoint.sh:/opt/samba/sam-ba_v3.9.2/entrypoint.sh
      - ./:/data

    entrypoint:
      - "./entrypoint.sh"
