services:
  gcuflashing:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcuflashing:latest
    container_name: gcuflashing
    network_mode: host
    group_add:
      - dialout
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    entrypoint:
      - "./entrypoint.sh"
    volumes:
      - ./entrypoint.sh:/opt/samba/sam-ba_v3.9.2/entrypoint.sh
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    stdin_open: true
